This is custom Exception here we created two programs 
